# Resources for OCRMill
from .styles import APP_STYLESHEET, HTS_DIALOG_STYLESHEET, DROP_ZONE_STYLES, THEME, COLORS, HTS_COLORS

__all__ = ['APP_STYLESHEET', 'HTS_DIALOG_STYLESHEET', 'DROP_ZONE_STYLES', 'THEME', 'COLORS', 'HTS_COLORS']
